name: "deploy"

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Webside deployment
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to dokku
        uses: dokku/github-action@master
        with:
          git_remote_url: "ssh://dokku@37.205.13.48:janlavicka-com"
          ssh_private_key: ${{ secrets.SSH_PRIVATE_KEY }}
